language: node_js
node_js:
  - "10"
services:
 - docker

before_install:
 - npm i -g npm@6.1.0
 - npm install

script:
 - npm run build
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 - docker build -t docker20200109/blog-editor:latest .
 - docker push docker20200109/blog-editor:latest